language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/user_on

node_js:  
  - "12.18.3"

before_script:
  - psql -c 'create database user_on;' -U postgres
  - psql -U postgres -d user_on -a -f table.sql

services:
  - postgresql